### PR TITLE
fix playerControls currently playing request

### LINKED ISSUE #27: decouple playerControls component in services

### PR DESCRIPTION
**Pull request by guilhermeabell**

### CODE REVIEW

File: src/components/PlayerControls/index.js [hunk 1]
```diff
@@ -26,24 +27,32 @@ export function PlayerControls() {
...
+    // if (response.data !== '') {
+    //   const { item } = response.data
+    //   const currentlyPlaying = {
+    //     id: item.id,
+    //     name: item.name,
+    //     artists: item.artists.map((artist) => artist.name),
+    //     image: item.album.images[2].url,
+    //   }
+    //   dispatch({ type: reducerCases.SET_PLAYING, currentlyPlaying })
+    // } else dispatch({ type: reducerCases.SET_PLAYING, currentlyPlaying: null })
```
Comment (alangabrielbs) [inline src/components/PlayerControls/index.js]: Remover comentarios

**Review by alangabrielbs — APPROVED** [review]
